### ISSUE TITLE
show mpv output (for debugging)

### ISSUE THREAD

**Issue by unhammer** [mihaiolteanu/vuiet#11]
I tried playing something, and nothing happened except the modeline changed. Then I tried the command from `vuiet--play-track` in the terminal and got a bunch of output from mpv (saying I needed to update youtube-dl :)). It would've been nice if there were a buffer showing such things that I could show with `vuiet-show-debug-output`. 

(Even nicer if vuiet itself could notice that something is wrong, but one thing at a time I suppose.)

**Comment by mihaiolteanu** [comment]
> It would've been nice if there were a buffer showing such things

I agree. Any suggestions on what to include in the debug output and/or how would one start to implement such a feature?

**Comment by unhammer** [comment]
I would just include anything that's output from mpv (e.g. what you get
when running it from the terminal), though I have no idea how to find
that using mpv.el

**Comment by mihaiolteanu** [comment]
Probably not gonna happen.
At least not in the near future.
