### ISSUE TITLE
Make versuri optional

### ISSUE THREAD

**Issue by DamienCassou** [mihaiolteanu/vuiet#12]
Hi,

I'm not interested in lyrics. Nevertheless, if I want to use vuiet, I need to first install versuri which itself has many dependencies I don't have installed yet (e.g., anaphora and esqlite).

Would it be possible to make the lyrics feature optional so I don't have to install all of that?

Thank you.

**Comment by mihaiolteanu** [comment]
Hello Damien,

No, that wouldn't be on my top priority list right now.
But nonetheless, do you know if there is an easy and bullet-proof method of doing this kind of thing that does not rely on hacks?

There are only two places where versuri is of interest, `vuiet-playing-track-lyrics` and  `vuiet-play-track-by-lyrics`. Both are interactive functions, so not requiring versuri wouldn't have much impact on the rest of vuiet. Still, I wouldn't know, as of now, how would one go about 'checking a box' and disabling this functionality for those who don't want it.

You don't have to install sqlite3 on your system if you never use those functions that I've mentioned above.

Please let me know what your ideas are,
Mihai

**Comment by DamienCassou** [comment]
> But nonetheless, do you know if there is an easy and bullet-proof method of doing this kind of thing that does not rely on hacks?

I tend to decompose my packages into several small files, each with a cohesive set of features. I would then have a `vuiet-lyrics.el` file which would  be the only one requiring `versuri` and no file requiring `vuiet-lyrics`. With some `;;;###autoload` cookies, this file would be automatically loaded when `vuiet-playing-track-lyrics` or `vuiet-play-track-by-lyrics` is called.

Another, simpler solution, is to only `(require 'versuri)` inside these 2 commands. No need to require it prematurely at the top of `vuiet.el`.

I don't see how a checkbox would help you. The use of the above commands is an implicit request for loading the feature.

**Comment by mihaiolteanu** [comment]
> Another, simpler solution, is to only `(require 'versuri)` inside these 2 commands.

This sounds like a hack to me. Nonetheless, your other solution might work, but I would have to say no at this moment. Sorry if this is a blocker for you.

Out of curiosity and for a better understanding of how others use and configure their Emacs, you would like to get rid of versuri and all of its dependencies because it increases the startup time with no actual benefit on your side?

Thanks for your input.

**Comment by DamienCassou** [comment]
it won't impact the startup time because these libraries will only be loaded when I first need their features. 

My problem is more that I don't want to let my Emacs depend on too many packages I don't control. With borg (https://github.com/emacscollective/borg), each of my Emacs' dependency is a git sub-module. I manually update each sub-module and read its commits so I have a clue about what is coming in. I'm happy to add more sub-modules for features I want (e.g., vuiet). I'm not happy to add sub-modules only because one package I would like happen to depend on them for features I don't care about.

**Comment by mihaiolteanu** [comment]
Sorry for the late reply.

> I'm not happy to add sub-modules only because one package I would like happen to depend on them for features I don't care about.

At the moment I'm considering the lyrics functionality as an integral part of what `vuiet` has to offer.
Unfortunately I do not plan on separating them at the moment Maybe in the future, when the package matures a bit and if becomes clear that not many people actually care about lyrics.
