### ISSUE TITLE
Title: Make vuiet configurable to use ivy or ido

### ISSUE THREAD

**Issue by tvraman** [mihaiolteanu/vuiet#15]
Description: Make completion interface configurable by:

1. Create a defcustom  vuiet-reader
2. Use (funcall vuiet-reader ...) in place of (ivy-read ...)
3. vuiet-reader can be ido-completing-read or ivy-read as examples
4. Once it's working, rename vuiet-*ivy* functions to vuiet-*read-*

**Comment by mihaiolteanu** [comment]
Closing, since there is no input on this.
