### ISSUE TITLE
Hydra for invoking vuiet

### ISSUE THREAD

**Issue by tvraman** [mihaiolteanu/vuiet#16]
Wrote this for emacspeak: feel free to borrow and modify if you think
it generally useful for vuiet.
https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-muggles.el#L772

**Comment by mihaiolteanu** [comment]
I'm not using hydra myself.

Are these kind of hydra heads provided directly by the packages, in general? Or does each user configure them in their own init file for each package?

If the first option is true, then the vuiet users who also use hydra can choose their own keybindings. I'll gladly accept the changes if you can reach a consensus regarding the bindings.

**Comment by tvraman** [comment]
title: Hydra for invoking vuiet
Hard to say what the right answer here is. For now I'm happy to keep the
hydra in the emacspeak-muggles package ---you could as a possibility
define the hydra in vuiet, but not bind it globally to a key, and leave
that to the user. that would be the equivalent of creating a vuiet minor
 mode, and letting the user choose the prefix key that invokes the minor
 mode.

**Comment by mihaiolteanu** [comment]
This is not an issue, it seems.
