### ISSUE TITLE
unable to get secret key to use vuiet extra services

### ISSUE THREAD

**Issue by eklebanow** [mihaiolteanu/vuiet#23]
I have vuiet working in doom emacs.  My lastfmrc is complete except for secret key (SK)

When I eval: (lastfm-generate-session-key) I get that the "token is unauthorized"

What does this mean?

**Comment by mihaiolteanu** [comment]
Did you follow all the steps? Did you grant your application permissions when the last.fm page asked you to?
Specifically, do you have anything in the Connected Applications list in your last.fm account: https://www.last.fm/settings/applications ?

**Comment by eklebanow** [comment]
I do not have anything in the connected applications list in my lastfm account.  Nowhere did it say that I have to do this......(maybe add it to your directions in the read me)

I am asked to Ginger it permission which I do... Then I get message that token is unauthorized

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mihaiolteanu** [comment]
The vuiet README specifically says you should follow the lastfm.el package README on how to install it.
Did you follow these steps: https://github.com/mihaiolteanu/lastfm.el#install ?
I agree that things can always be made more clear :)

**Comment by eklebanow** [comment]
I added the scribble Spotify....connecting it to my lastfm account .  I tried again and I still get unauthorized token

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mihaiolteanu** [comment]
Did you follow these steps: https://github.com/mihaiolteanu/lastfm.el#install ?

**Comment by eklebanow** [comment]
I think I followed the steps...
Now that I have connected scrobble Spotify do you think there is a delay before my token is authorized?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mihaiolteanu** [comment]
I think you did not. There is no mention of Spotify in there.
I cannot help you if you do not want to follow the steps written in the README.

**Comment by eklebanow** [comment]
I did follow steps in read me.

In your first email you asked if I had connected any app... As if you need too... So I followed the link you provided and connected the scrobble Spotify app.  Is that what you meant?  Do I need to have a connected app for is having a connected app NOT what I want?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mihaiolteanu** [comment]
Do you have the API-KEY in your .lastfmrc file?

**Comment by eklebanow** [comment]
Yes

Everything is working in vuiet except for the add ons you get with the SK.... Which I cannot seem to get because the token is unauthorized....

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mihaiolteanu** [comment]
If you would, then you would also have something in the Connected Applications, since lastfm asks you for the name of your application when you apply for an API-KEY. I believe you did not do those steps in the link I've sent you two times already.

I'm sorry, but I cannot help you if you don't read the documentation first.

**Comment by eklebanow** [comment]
Maybe that's the problem.... When it asked for the name of the application I just made up some jibberish...I did not know what to do at that step and your readme did not tell me what to do as far as making an application....I am a noob at computer stuffy

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
