### ISSUE TITLE
unable to get authorized token from lastfm

### ISSUE THREAD

**Issue by devereaux365** [mihaiolteanu/vuiet#28]
In my attempts to get a secret key (SK) to be able to use all of vuiets functionality, I am unable to get an authorized token. I followed the directions in your lastfm README.  I received an api and a shared secret, I connected an app (Spotify scrobbler).  When eval in emacs (lastfm-generate-session-key) I am asked if I want to grant access to which I answer yes......I get back a message unauthorized token....

Is this a lastfm issue?  googling in the past there was a problem with lastfm not authorizing tokens....

**Comment by mihaiolteanu** [comment]
Seems like you really are in a bad luck here.
