### ISSUE TITLE
Cannot play tracks until restart emacs

### ISSUE THREAD

**Issue by shevchuk** [mihaiolteanu/vuiet#29]
Sometimes something happens and I cannot manage to make vuiet play tracks until I restart emacs. Killing processes doesn't help. This starts to happen in the recent version (the one that fixed the problem with mpv process delays)

**Comment by mihaiolteanu** [comment]
Not even after you do a `vuiet-stop`?

**Comment by shevchuk** [comment]
Yes, vuiet-stop doesn't help. But I will try to reproduce it today, can you give me some hints on what I should output for the debugging purposes ?

**Comment by mihaiolteanu** [comment]
1. Call `list-processes` after `vuiet-stop`. Are `mpv-player` and `mpv-socket` still alive? They shouldn't be and calling any vuiet function that starts a playlist should start mpv anew.

2. Are you using `vuiet-update-mode-line-automatically`? Enabling this will start a timer that will call `vuiet-update-mode-line` regularly. If you start more than one timer, but don't stop any, I think there is a possibility that your Emacs might block. `vuiet-stop` should actually kill this timer, and I've put checks to ensure only one timer can be stared, but who knows. (https://github.com/mihaiolteanu/vuiet/blob/master/vuiet.el#L395)

3. Are you sure it's not something from the lastfm package? I haven't changed anything in there, but if lastfm can't return any tracks, there is nothing vuiet can play, thus, vuiet might be started and mpv is running but it has an empty playlist.

4. In the worse case, you can edebug `vuiet--play`. This is the main entry point for everything related to playing tracks. (https://github.com/mihaiolteanu/vuiet/blob/master/vuiet.el#L690)

Let me know if you find anything or if you have additional info.

**Comment by mihaiolteanu** [comment]
I think I found the bastard.
It was indeed the timer. Or, better yet, trying to do something with a nil object, which gives an error.

I've pushed the update.

**Comment by shevchuk** [comment]
Awesome, I think it is much more stable now!
