### ISSUE TITLE
cannot find certain versions of songs

### ISSUE THREAD

**Issue by eklebanow** [mihaiolteanu/vuiet#30]
Trying to be able to listen to the alchemy version of the dire straits song "sultans of swing" but I cannot seem to bring it up on vuiet...either by vuiet play track (limited to 15 listings) or play album (limited to 10 listings)

Is there a way to bring up additional tracks or albums or is the user of vuiet limited to the stated number?

**Comment by devereaux365** [comment]
I changed the variable of the play track function to 50.. Which brought up additional dire straits songs but not what I wanted.  I could not change the album number.  The song I want is on the alchemy live album.  The album is listed on last fm

**Comment by mihaiolteanu** [comment]
Try `vuiet-play-track-search`.

But there is nothing on that album to distinguish that song that it is special (https://www.last.fm/music/Dire+Straits/Alchemy).
Youtube would still search for "Dire Straits - Sultans of Swings", since that it the actual name of the song on that album.

**Comment by eklebanow** [comment]
Thanks... That worked... Using vuiet play track search I was able to get the version I wanted....

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
