### ISSUE TITLE
Artist info: square bracket in Org link

### ISSUE THREAD

**Issue by firmart** [mihaiolteanu/vuiet#33]
On the page of Pierre Hantaï, there is a track containing square brackets. 

![image](https://user-images.githubusercontent.com/20540328/106369493-3c981500-6352-11eb-8673-3e3ececbdf9c.png)

Do you think there is any means to fix it ? It looks like rather an Org mode issue.
BTW, in my opinion artist info buffer (and maybe others) should be made read-only.

**Comment by firmart** [comment]
Maybe we can use special Unicode to replace square brackets in a first place and replace it back when calling `vuiet-play` or `vuiet-play-album`.

**Comment by mihaiolteanu** [comment]
Maybe just replace `[Introduction]` with `(Introduction)`.
It should make no difference to youtube if you have square or round brackets in your search string.

I can't think of any other bad influence this might have on the rest of `vuiet`. Do you see any?

**Comment by firmart** [comment]
No, I don't see any, but mostly because I started using vuiet & lastfm 2
days ago... 

As it involves replacing [] to () in multiple places in the source code,
we might want to wrap the snippet which builds an Org link into a
function to reduce redundancy and to make sure we are done we this
issue. We can also use the function `org-make-link-string`. BTW, I think
the requirement of Org is missed at the top of vuiet.el.

**Comment by mihaiolteanu** [comment]
> As it involves replacing [] to () in multiple places in the source code,
> we might want to wrap the snippet which builds an Org link into a
> function to reduce redundancy and to make sure we are done we this
> issue.

Agree. If you can find a nice solution to it, let me know and I'll merge it.

> I think the requirement of Org is missed at the top of vuiet.el

True. Though I'm not sure you need to, it being part of Emacs. I might be mistaken, though.
