### ISSUE TITLE
Feature request: customize vuiet mode-line 

### ISSUE THREAD

**Issue by firmart** [mihaiolteanu/vuiet#34]
I wanted to keep my `vuiet` mode-line information on the top of my buffer (my mode-line is too long). So I ended up to something like this:
```lisp
(setq header-line-format '((:eval mode-line-misc-info)))
```
However, vuiet still append my bottom mode-line (which is normal). I would want to have that information on the top only. To do this, I think it would be nice if the lines I quote below are separated in another function (say `vuiet-mode-line-info`). Then with an additional customizable variable which enable/disable vuiet mode-line information (say `vuiet-append-mode-line`), I would be able to reach what I was looking for with something like

```lisp
(setq header-line-format '((:eval (vuiet-mode-line-info))))
(setq vuiet-append-mode-line nil)
```

https://github.com/mihaiolteanu/vuiet/blob/3dab1ea2253d5bc2974a1a064d2b1af3bd6b24f6/vuiet.el#L434-L444

**Comment by mihaiolteanu** [comment]
Nice! I haven't even thought about putting that info in the header.
If you can implement it so that the user can pick where to display the info, that would be fine by me.
Of course, this would need updates to all the places where the mode-line is updated, plus the README.

Something like,
```
(defcustom vuiet-mode-line-position "bottom"
  "Position of the currently playing track info: "bottom/up/none."
  :type '(string :tag "position")
  :group 'vuiet)
```

**Comment by mihaiolteanu** [comment]
Closed due to lack of activity.
