### ISSUE TITLE
Readme needs updating

### ISSUE THREAD

**Issue by michaelmrose** [mihaiolteanu/vuiet#4]
Starting up using this library is unduly challenging as basic functionality is out of step with functions described in the readme.

Example: (vuiet-play-tag-similar "rock,punk") works because it expects a string that is split on commas rather than '("rock" "punk") 

Thanks for making this looks like has a ton of potential

**Comment by mihaiolteanu** [comment]
> Example: (vuiet-play-tag-similar "rock,punk") works because it expects a string that is split on commas rather than '("rock" "punk")

True. Good find! What would you say would be better, different arguments or a string separated by commas?

Let me know if you find other such inconsistencies.

**Comment by unhammer** [comment]
I would prefer `(vuiet-play-tag-similar '("rock" "punk"))` – string-parsing feels like a code-smell. (Another option is `(vuiet-play-tag-similar "rock" "punk")` etc., but that makes it impossible to later add optional arguments.)

**Comment by mihaiolteanu** [comment]
> I would prefer `(vuiet-play-tag-similar '("rock" "punk"))` – string-parsing feels like a code-smell. (Another option is `(vuiet-play-tag-similar "rock" "punk")` etc., but that makes it impossible to later add optional arguments.)

Agree. I've kept the `(vuiet-play-tag-similar '("rock" "punk"))` variant when the arguments are passed directly and the comma variant when the functions are called interactively.

Let me know how that works out for you.

**Comment by unhammer** [comment]
That sounds great =D

**Comment by mihaiolteanu** [comment]
I'll close this issue since there seems to be no other requests at the moment.
Feel free to open another ticket if you encounter such issues in the future.

Thank you!
