### ISSUE TITLE
Remove empty album/track from artist info buffer

### ISSUE THREAD

**Issue by firmart** [mihaiolteanu/vuiet#41]
For instance https://www.last.fm/music/%E4%B9%85%E7%9F%B3%E8%AD%B2/(null) is an empty/removed album which appears when doing
```lisp
(lastfm-artist-get-top-albums "久石譲")
``` 

I didn't find other examples so far, so I'm not confident enough to generalize it (*e.g.* remove all `(null)` album).

**Comment by firmart** [comment]
There are a bunch actually: [Search results for “(null)”](https://www.last.fm/search/albums?q=%28null%29 )

**Comment by mihaiolteanu** [comment]
> There are a bunch actually

There a quite a few (null) albums out there, given that there are probably tens of millions of albums on last.fm.
I'm not sure what the meaning of (null) album is on last.fm. Maybe this is just a glitch?! After all, anybody can add anything they want. Any more glitches out there?! Could be useful, indeed, to remove these.

**Comment by firmart** [comment]
Yeah, another issue, beside they are ugly, is that they are not playable. And for now I think
that vuiet doesn't catch such error (e.g. this album is empty!).
I don't know how to fix elegantly this issue, I added in the insert loop

     unless (string= (car album) "(null)")

in my local version, but the problem is that the numbering is messed
up. Maybe is better to filter them out in lastfm.el, but it may be
difficult are all functions are built from macro.

**Comment by mihaiolteanu** [comment]
Closed due to lack of activity.
