### ISSUE TITLE
Question: `(mpv-run-command "playlist-play-index" index)`

### ISSUE THREAD

**Issue by firmart** [mihaiolteanu/vuiet#48]
I'm working on a playlist interface using [hydra](https://github.com/abo-abo/hydra). For now, It roughly looks like this: a pop-up window displaying playlist's items on which the user can select by number the item they want to play. 

![Screenshot from 2021-02-01 23-59-58](https://user-images.githubusercontent.com/20540328/106528962-f37ac900-64e9-11eb-8571-2e1d6e58d2a8.png)

I need to play an item on the playlist given an index. So, for instance to play the first track of the playlist, I tried 

```lisp
(mpv-run-command "playlist-play-index" 0)
```

But I received the error 
```
Debugger entered--Lisp error: (error "‘playlist-play-index’ failed: invalid parameter")
```

Any clue on what I'm doing wrong ?

**Comment by mihaiolteanu** [comment]
Where is the list that you're trying to play with the "playlist-play-index" coming from?

**Comment by firmart** [comment]
It's the current playlist of vuiet. I wonder why (mpv-run-command
"playlist-next") works but not playlist-play-index.

**Comment by mihaiolteanu** [comment]
Please explore `vuiet` a bit deeper. :)

**Comment by firmart** [comment]
Sorry, I'm not sure what are you suggesting. Do you mean that the answer resides in `vuiet` and I'm missing something obvious ?
To be precise, I'm referring to the currently playing mpv playlist under the control of `vuiet`.

**Comment by mihaiolteanu** [comment]
Well, yes, but the currently playing playlist is not the same as with the mpv playlist.

> the user can select by number the item they want to play

You can use `vuiet-play-track` instead, to play any item you want from that list.

**Comment by firmart** [comment]
`vuiet-play-track' is not what I'm looking for because it resets the
current playlist AFAIK. What I'm doing here is implementing the
possibility to navigate through the current underlying mpv
playlist. Precisely, user can select by a digit (cf. picture above) the
track of the current vuiet playlist. To do that, I have to be able to
jump between track given a playlist index. This is exactly what
playlist-play-index is supposed to do, but I can't make it works for
some reason.

**Comment by mihaiolteanu** [comment]
`playlist-play-index` can only refer to items already in the mpv playlist. Correct?
When you play a list with vuiet, say an artist's album, it only adds the first track to the mpv playlist and sets an event hook. That event is the `playback-restart` which is called when a track starts playing. And what happens when a new track starts playing? vuiet takes the next track from the artist's album and adds it to the mpv playlist. So while the first track is playing only the next one is available in the mpv playlist. If you now try to play the index 5, it doesn't exist, since it was not added yet.

Does that make sense?
If yes, can you figure out why I can't add all the tracks to mpv (all the tracks from an artist's album, for example) in one go?

**Comment by firmart** [comment]
Yes, you confirmed what I understood. I observed what you said when I
was writing this snippet: it indeed loads the next track gradually. I'm
actually trying to play track already present in the playlist. The
tracks you are seeing in the picture is tracks already played. I'm not
trying to play tracks not added. So my question is still relevant: why
playlist-play-index doesn't work on existing track on the playlist ? Do
you observe the same issue in your side ?

To reproduce my issue: play anything with vuiet and eval 

(mpv-run-command "playlist-play-index" 0)

which should work no matter what, right ?

In fact, even 

(mpv-run-command "playlist-play-index" (mpv-get-property "playlist-pos"))

doesn't work (same error).

**Comment by mihaiolteanu** [comment]
True, it doesn't work on my side, either. I get the same error
Not even `(mpv-run-command "playlist-play-index" "current")`, which should be available regardless of the playlist (since the current index is always available),
https://mpv.io/manual/master/#command-interface-playlist-play-index

What you can try is to test mpv from the command line and see if that works. That is, outside the emacs context.
If it works, it might be a problem from the mpv.el library itself?! Maybe the way `mpv--enqueue` encodes the command parameters given to mpv?!

> Where is the list that you're trying to play with the "playlist-play-index" coming from?

> The tracks you are seeing in the picture is tracks already played. I'm not trying to play tracks not added.

We've managed to understand each other, eventually. :)

**Comment by firmart** [comment]
I will give more feedback later, but for now it seems that my mpv is too
old.  playlist-play-index is introduced in version 0.33 (see
https://github.com/mpv-player/mpv/commit/e9e93b4dbe748cd341a6fbea355e6ba013ada81b)
But my version is 0.32.

> We've managed to understand each other, eventually. :)

Yeah, it's good to clarify things gradually as we have done. BTW, this
package is truly amazing! Especially the use of Org mode as info
buffer. I quickly abandoned other music players because their playlists
buffer was not straightforward enough to my taste.

**Comment by mihaiolteanu** [comment]
Oh, crap! Mine is 0.29. Good find!
Well, at least we know where the `(error "‘playlist-play-index’ failed: invalid parameter")` comes from.

Yes, "[everybody](https://www.reddit.com/r/emacs/comments/fl6vbu/vuiet_the_music_player_and_explorer_for_emacs/fkwypyb?utm_source=share&utm_medium=web2x&context=3)" seems to like the org feature, which is great (I like it too!), but I haven't got any love for the lyrics feature. Presumably, you could download the lyrics for all your loved tracks and artists and then play by lyrics. I haven't explored this myself to its full potential, either. It's just there, waiting to be used and abused.

Back to org and hydra, maybe it would be useful to add some hydra heads to the `vuiet-artist-info` org buffer?
There are already some features on that org buffer, like pres `s` for "select and display info for a similar artist with ivy" and the like (interestingly, selecting an album is missing),
https://github.com/mihaiolteanu/vuiet/blob/master/vuiet.el#L208 

Similar for `vuiet-album-info` buffer,
https://github.com/mihaiolteanu/vuiet/blob/master/vuiet.el#L341

It would make discovering new features more easy in those org buffers. Maybe have the same key (space, enter, h...whatever) work as a hydra leader key in all these org buffers?!
Just some ideas.

Anyway, thanks for having a look at vuiet and fixing the issues.
That's really helpful!

**Comment by firmart** [comment]
I have only tried `vuiet-playing-track-lyrics` a bit. I got an encoding issue (was CJK lyrics) which I wasn't able to track quickly since the source of the lyrics is randomly chosen. But yeah, is a good feature which has lots of potential. I will take a look when the time comes.

Concerning the info buffer, as an `evil` user, I have to switch to Emacs state to use the local map. I use `general` to map all available functions. But it is less handy when it comes to local map. Maybe we need minor mode map for artist/album info so that anyone can bind the key binding as they wish ? It would also be nice to show the local/major key binding somewhere through hydra or something else. Anyway I will open other issues to discuss this separately.

**Comment by firmart** [comment]
For the record:

```lisp
  (defun mpv-version ()
    "Return mpv version."
    (interactive)
    (let ((version (cadr (split-string (car (process-lines "mpv" "--version"))))))
      (prog1 version
	(if (called-interactively-p 'interactive)
	    (message "%s" version)))))

  (defun my/mpv-playlist-play-index (pos)
    (let ((cur (mpv-get-property "playlist-pos")))
      (if (version<= "0.33" (mpv-version))
	  (mpv-run-command "playlist-play-index" pos)
	(cl-loop repeat (abs (- pos cur))
		 do (sleep-for 0.10)
		 if (> cur pos) do
		 (mpv-run-command "playlist-prev")
		 else do
		 (mpv-run-command "playlist-next")))))

```

**Comment by mihaiolteanu** [comment]
You mean to load all the songs in your list into mpv until you reach your desired index?
Meaning, if mpv is playing from index 0, but you want now to play index 5, will mpv load all the songs from 0 to 5?

I think `mpv-version` would better be placed in https://github.com/kljohann/mpv.el, right?

**Comment by firmart** [comment]
> I think `mpv-version` would better be placed in https://github.com/kljohann/mpv.el, right?
Yeah, I already made a PR at kljohann/mpv.el.

> You mean to load all the songs in your list into mpv until you reach your desired index?
> Meaning, if mpv is playing from index 0, but you want now to play index 5, will mpv load all the songs from 0 to 5?
Well, I always worked with already loaded songs. The function above is
just an mpv wrapper. In the context of vuiet, if one play an album in
which songs are loaded gradually, I guess that, yes, it will load all
the songs from 0 to 5. But we won't let this happen unless it is
worthwhile. My hydra playlist interface, only displays already
loaded songs. So it won't load any new songs aggressively.
