### ISSUE TITLE
Symbol’s value as variable is void: vuiet--make-generator

### ISSUE THREAD

**Issue by chenyanming** [mihaiolteanu/vuiet#5]
When I ` (require 'vuiet)`

I got the the error: `Symbol’s value as variable is void: vuiet--make-generator`, how to fix it?

Besides, I have setup lastfm and I can get the artist info:
![image](https://user-images.githubusercontent.com/3462132/77132496-abea7a80-6a9a-11ea-82e7-4ee82767d5e8.png)

And when I press enter on one of the top songs, I got the error: `eval: Symbol’s function definition is void: vuiet-play`
![image](https://user-images.githubusercontent.com/3462132/77132522-ce7c9380-6a9a-11ea-86dc-ef87ecad2cbb.png)

**Comment by chenyanming** [comment]
Besides, it seems that it can not support  chinese?

**Comment by mihaiolteanu** [comment]
> Besides, it seems that it can not support chinese?

I think this has to do with your Emacs setup and not with vuiet?! Though, I assume your Emacs displays chinese characters just fine on other buffers. Anyway, here is how it looks for me
![screenshot1584687837](https://user-images.githubusercontent.com/8273519/77142759-c700be80-6a89-11ea-8e5d-2df2ec4aff14.png)

Let me know if you find a solution for this on your side.

**Comment by mihaiolteanu** [comment]
> I got the the error: `Symbol’s value as variable is void: vuiet--make-generator`, how to fix it?

Interesting. Can you please go to where vuiet.el is installed on your machine and try to evaluate that buffer. All the functions should be in there, including vuiet--make-generator and vuiet-play, which you also said is not available.

That is, go to ~/.emacs.d/elpa/vuiet-20200318.753/vuiet.el and then call M-x eval-buffer from inside vuiet.el. Let me know what happens after that. Either you get some errors right away, either the above mentioned functions are now available.

**Comment by aluaces** [comment]
@chenyanming: your problem is fixed in #6.

**Comment by mihaiolteanu** [comment]
I'm assuming this is fixed. Please reopen if you have any more issues.
