### ISSUE TITLE
Feature request: Track looping?

### ISSUE THREAD

**Issue by LemonBreezes** [mihaiolteanu/vuiet#52]
Often times when I play a single track, I like to loop the song. It would be nice if there were a variable that made tracks auto-loop. :)

**Comment by mihaiolteanu** [comment]
Rather like a command, I would guess.
It could happen that you're listening a whole album, or random tracks or something similar. And you find a song that you want to play over and over again. Would that be a reasonable scenario? Would `vuiet-replay` not be enough? (yes, you need to call it every-time, but at least it replays the same track).

I haven't had that urge, to be honest. So, we'll see. :)

**Comment by LemonBreezes** [comment]
A command would be alright too. The problem with `vuiet-replay` is that I often get really focused on my work so when the song ends I work in silence, fearing that if I replay the song I will lose that fleeting thesis solution.

Wow, I can't believe this entire time I have only been playing single tracks. :laughing:

**Comment by mihaiolteanu** [comment]
:))
You really need to read the complete functionality, then,
https://github.com/mihaiolteanu/vuiet#complete-functionality

There are some nice bits in there.

**Comment by mihaiolteanu** [comment]
@firmart what do you think?

**Comment by firmart** [comment]
Maybe we can bring here some ideas of [ncmpcpp](https://github.com/ncmpcpp/ncmpcpp#readme). It has some key bindings among other allowing to toggle 
- Repeat mode
- Single mode

By combining them, one can loop a track or a whole playlist. Precisely,
- To repeat a whole playlist, one should have "repeat mode" on and "single mode" off.
- To repeat a single track, set both "repeat mode" & "single mode" on. 

It would not be too hard to implement this feature. My only concern is that I don't know how to detect elegantly the event "playback of the current track has ended" to thus be able to decide the next track to play.

**Comment by mihaiolteanu** [comment]
True, figuring out when a track has ended is a bit of a challenge.
I'm currently using the `file-loaded` event from mpv to figure out when the next track has started playing (which would mean the previous one has just ended), and start preloading the next track, and so on and so forth. But I guess you're already familiar with that.

Maybe there are some other events in there that I haven't tried,
https://mpv.io/manual/master/#list-of-events

**Comment by mihaiolteanu** [comment]
No go due to the added complexity for little gain.
