### ISSUE TITLE
vuiet-play-track-search failed when there is only one result

### ISSUE THREAD

**Issue by firmart** [mihaiolteanu/vuiet#53]
This is rather a lastfm.el issue.

I take an extreme case here, try to evaluate

```lisp
(vuiet-play-track-search "Watch A Reporter’s Footage from Inside the Capitol Siege | The New Yorker Video | CNE | Newyorker.com | The New Yorker")
```
It will give `Debugger entered--Lisp error: (wrong-type-argument listp "Newyorker.com")` because 

```lisp
(lastfm-track-search "Watch A Reporter’s Footage from Inside the Capitol Siege | The New Yorker Video | CNE | Newyorker.com | The New Yorker")
```
returns 

```lisp
("Newyorker.com" "Watch A Reporter’s Footage from Inside the Capitol Siege | The New Yorker Video | CNE | Newyorker.com | The New Yorker")
```
instead of a list of lists.

(I know that this is not a song, but I succeed to hit this bug with a rare song).

I believe that the cause comes from the following lines in `lastfm--parse-response`:
```lisp
          ;; Responses with only one entry, such as artist-info, don't need to
          ;; be transformed but returned as a simple list of strings.
          (-flatten parsed-response)
```

https://github.com/mihaiolteanu/lastfm.el/blob/276c30a16518e545c95b7d693bada3ec01ddd207/lastfm.el#L551-L553

Other functions which expect a playlist (songs) could hit this bug.  

If modifying lastfm.el is too complicated, we could fix functions which expect a playlist (e.g. vuiet--ivy-play-song).

**Comment by mihaiolteanu** [comment]
> If modifying lastfm.el is too complicated

Yes, that could be a bit complicated.
Good find!
But the #54 solution is also a bit too complicated.

Wouldn't something like this suffice?
```
(defun vuiet-play-track-search (track)
  (interactive "sTrack: ")
  (let ((tracks (lastfm-track-search track)))
    (if (listp (car tracks))
        (vuiet--ivy-play-song tracks)
      ;; last.fm returned only one result, which is not a list of tracks.
      (vuiet--ivy-play-song (list tracks)))))
```

or do you see other fail points here?

**Comment by mihaiolteanu** [comment]
Implemented with the simplified proposal.
