### ISSUE TITLE
Feature request: Info buffer: back navigation

### ISSUE THREAD

**Issue by firmart** [mihaiolteanu/vuiet#55]
At present, we can navigate through tag and artist on artist/tag info buffer. But we cannot navigate backward through the history.

**Comment by mihaiolteanu** [comment]
I think the artist info buffer (and the like) open up a new info buffer when you click an element from it.
Closing the new info buffer still keeps the old one open.

**Comment by firmart** [comment]
Yeah, so I'm thinking of keeping a stack to store e.g. searched artists
and add a function or local keybinding to come back the last info
buffer. If the old buffer is not killed, simply switch to it. Otherwise,
refetch the info buffer.

**Comment by mihaiolteanu** [comment]
I think this is overkill.
Every new feature complicates the implementation as well.
It's nice and fun when you implement it, not so when you come back to it later or something is broken.

**Comment by firmart** [comment]
Well, in this particular case I do not agree. In contrast to other PRs
which look complicated, and they are, this one is just a matter of a few
lines. But it's your package after all. You decide.
