### ISSUE TITLE
Bug: `vuiet-info-playing-track-album' fails when current track has no album

### ISSUE THREAD

**Issue by firmart** [mihaiolteanu/vuiet#56]
Similar to bug #53 due to lastfm.el inconsistency. 

Because 
```lisp
(lastfm-track-get-info artist song)
```
returns the list `(album playcount listeners)` if there is an album, and `(playcount listeners)` if there is not.

Solution: either fix it upstream in lastfm.el (e.g. return `(nil playcount listeners)`) or type check the result of `lastfm-track-get-info`. This issue may occur in several places (e.g. `vuiet-play-playing-track-album`).

**Comment by mihaiolteanu** [comment]
> either fix it upstream in lastfm.el (e.g. return (nil playcount listeners))

Definitely the preferred solution.
Please let an example, also.

**Comment by mihaiolteanu** [comment]
Closed: solved with #53
