### ISSUE TITLE
Feature request/suggestion: show albums on Artist buffer and increase album limit

### ISSUE THREAD

**Issue by jjnilton** [mihaiolteanu/vuiet#67]
Currently the Artist buffer lists the Top Songs, but not the Top Albums. I think that listing the Top Albums could be useful to people who like to listen entire albums, or just want to listen a track in a specific album.

I don't know Elisp, but could get what I wanted adding this code:

```
      (insert "\n* Top Albums: \n")
      (setq-local albums (lastfm-artist-get-top-albums artist))
      (cl-loop for i from 1
               for album in albums
               do (insert (format "%2s. [[elisp:(vuiet-album-info \"%s\" \"%s\")][%s]]\n" i artist (car album) (car album))))
```

Another thing that I think that could be helpful is to display the keybindings to the actions in the buffer.

I added this to the album buffer in case I forget the keybindings:

```
      (insert "\n[s] choose a song with ivy | [a] pick another album | [p] play album | [l] save lyrics")
```

And on `lastfm.el` I changed the limit of `artist.getTopAlbums` to 20: `(lastfm--defmethod artist.getTopAlbums (artist (limit 20))` but maybe a custom option would make it more accessible.

It also could be helpful to mention somewhere about the `org-babel-confirm-evaluate`, in case one want to interact with the buffer without having to confirm every action.

Thanks for sharing the package.

**Comment by mihaiolteanu** [comment]
> I think that listing the Top Albums could be useful to people who like to listen entire albums

I agree so, too. The current implementation is a compromise, as there is no last.fm call that includes both the top songs and top albums. As you can confirm with your own implementation, this needs an additional last.fm call, which slows things down. I could definitely add an option for the user to select which info he/she wants to see. 

> Another thing that I think that could be helpful is to display the keybindings to the actions in the buffer.

Yes, I'm not remembering them either :)) The solution would be to implement a new major mode, bind some keys to it and then those keys would be available through other means (C-h m, for example). This was suggested by another user, actually. So definitely something that could be improved.

**Comment by mihaiolteanu** [comment]
I've added both features related to albums info. There are now two extra defcustom variables. Their default values keep the old functionality.

```
vuiet-artist-top-albums-limit
vuiet-artist-info-show-top-albums
```

Please check the README, test the functionality and confirm that it works as expected.

**Comment by jjnilton** [comment]
Thanks a lot, it's great to have this option, and to list more albums as well.

When I try to use the link on the org buffer I get the following error message though:
```
Debugger entered--Lisp error: (wrong-type-argument stringp t)
  format-message(t)
  apply(format-message t)
  error(t)
  lastfm--parse-response("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<lfm status=\"failed\"><error code=\"6\">The artist you supplied could not be found</error>\n</lfm>\n" ("album > name"))
  lastfm-artist-get-top-albums((("weezer" "Pinkerton")) :limit 30)
  (ivy-read (format "%s Album:" artist) (lastfm-artist-get-top-albums artist :limit vuiet-artist-top-albums-limit) :action #'(lambda (a) (setq album (car a))))
  (if album nil (ivy-read (format "%s Album:" artist) (lastfm-artist-get-top-albums artist :limit vuiet-artist-top-albums-limit) :action #'(lambda (a) (setq album (car a)))))
  vuiet-album-info((("weezer" "Pinkerton")))
  eval((vuiet-album-info '(("weezer" "Pinkerton"))))
  org-link--open-elisp(#("(vuiet-album-info '((\"weezer\" \"Pinkerton\")))" 0 44 (face org-warning)))
  org-link-open((link (:type "elisp" :path #("(vuiet-album-info '((\"weezer\" \"Pinkerton\")))" 0 44 (face org-warning)) :format bracket :raw-link "elisp:(vuiet-album-info '((\"weezer\" \"Pinkerton\")))" :application nil :search-option nil :begin 2440 :end 2505 :contents-begin 2494 :contents-end 2503 :post-blank 0 :parent (paragraph (:begin 2440 :end 2506 :contents-begin 2440 :contents-end 2506 :post-blank 0 :post-affiliated 2440 :parent (item (:bullet "4. " :begin 2436 :end 2506 :contents-begin 2440 :contents-end 2506 :checkbox nil :counter nil :structure (... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) :pre-blank 0 :post-blank 0 :post-affiliated 2436 :tag nil :parent (plain-list ...))))))) nil)
  org-open-at-point(nil)
  funcall-interactively(org-open-at-point nil)
  call-interactively(org-open-at-point nil nil)
  command-execute(org-open-at-point)
```

I changed this line https://github.com/mihaiolteanu/vuiet/blob/master/vuiet.el#L283 to:

```
                     (format "%2s. [[elisp:(vuiet-album-info \"%s\" \"%s\")][%s]]\n"
```

And it worked, but not really sure why.

**Comment by mihaiolteanu** [comment]
I know why! You do know a little bit of elisp, don't you? :)
`vuiet-album-info` expect two parameters not a list. My implementation was wrong. Yours is correct.

I've updated it. Thanks for the feedback!

**Comment by jjnilton** [comment]
I'm still getting started with elisp, so there's a long way to go.

Now I see, I was a bit confused about the list syntax. Thanks for explaining it!

Thanks!
