### ISSUE TITLE
vuiet uses ivy without a package dependency on it

### ISSUE THREAD

**Issue by catern** [mihaiolteanu/vuiet#68]
If I package-install vuiet, then vuiet-play-album and hit tab, I get an error about missing ivy functions. So I had to explicitly package-install ivy as well. vuiet should depend on ivy if it uses it automatically.

Related also to #15; vuiet could avoid depending on ivy if it used the emacs completion interface `(info "(elisp) Completion")` instead of hardcoding ivy.

**Comment by mihaiolteanu** [comment]
Definitely something to consider. I haven't used completing-read myself nor is this on my high-prio tasks at the moment.

Accepting PRs.

**Comment by thriveth** [comment]
I agree that completing-read would be great, but I think as a minimum Vuiet should depend on Ivy on install, since it does depend on it to run.

**Comment by mihaiolteanu** [comment]
Updated.
Thanks for bumping this up!
