### ISSUE TITLE
Autodetect using yt-dlp instead of youtube-dl

### ISSUE THREAD

**Issue by catern** [mihaiolteanu/vuiet#69]
The main youtube-dl project, as I understand it, has minimal active maintenance.  The most active fork, yt-dlp, doesn't install a "youtube-dl" command, but instead calls its command "yt-dlp".  vuiet.el should automatically use yt-dlp if it's present on PATH and youtube-dl is not.

**Comment by mihaiolteanu** [comment]
> The main youtube-dl project, as I understand it, has minimal active maintenance.

Source? The last commit is from 9 days ago.

> The most active fork, yt-dlp, doesn't install a "youtube-dl" command, but instead calls its command "yt-dlp"

How is that any different/better?

Since it doesn't fix anything for us, but it would definitely require a time investment in testing, I don't see any reason for the switch.

**Comment by magicaldave** [comment]
This is an old issue but as I understand it Youtube-dl now has issues with downloading certain videos and will complain about them being age-restricted, without some additional setup on the user's part. Yt-dlp does not have this limitation.

**Comment by mihaiolteanu** [comment]
Looks like development on youtube-dl has stopped, indeed.
I will check this out as soon as possible.

If any of you have a fix in the meantime, I'll consider a PR.
Edit: this would include testing, of course

In the meantime, the `vuiet-youtube-dl-command` can be changed to `yt-dlp` if you so please since it is a custom variable.

**Comment by magicaldave** [comment]
It could potentially be useful but to switch between the two, but due to the regularity with which Youtube breaks things, perhaps the best option would be to set the default for said variable to yt-dlp and change the dependency going forward.
