### ISSUE TITLE
Use (interactive) descriptors rather than calling ivy-read explicitly

### ISSUE THREAD

**Issue by catern** [mihaiolteanu/vuiet#70]
Commands such as vuiet-play-artist call ivy-read internally. This makes them not able to be repeated with `C-x z` or `C-x M-:` because they prompt for input again. If (interactive) descriptors are used (see `C-h f interactive`), these commands can be repeated with the same input using the existing Emacs infrastructure for doing so.

**Comment by mihaiolteanu** [comment]
I'm not sure exactly what you are suggesting.
