### ISSUE TITLE
Wrong Type Argument on Function Calls

### ISSUE THREAD

**Issue by magicaldave** [mihaiolteanu/vuiet#71]
Hello, after recently installing vuiet, many functions return the following error:
![image](https://user-images.githubusercontent.com/73663882/195256278-874a1954-41e3-495b-afad-05e9013b420a.png)
This is what happens just after playing a song, which does work.
Some other functions, like searching songs by lyrics or 'loving' a track return a similar error:
`wrong-type-argument stringp t`

**Comment by mihaiolteanu** [comment]
Please check out issue #66 for a similar problem.

Specifically this line,

> So I asked for a new API key and configured it again, this time confirming in the Last.fm page before answer 'yes' to the prompt in emacs, and it seems to be solved. So I guess the issue was the API key.

Let me know if you're still experiencing it.

**Comment by magicaldave** [comment]
Okay, so I generated a new API Key and Shared Secret, and put that into my ~/.config/.lastfmrc
This is where things get screwy like last time.
I used `M-:` to eval (lastfm-generate-session-key) and I get the prompt to accept it in emacs, but my browser doesn't do anything.
So I manually navigated to `http://www.lasfm/api/auth/?api_key=xxx` with the new API key there. It asks if I want to allow the application, I hit yes, and I get a page that says invalid api key, and press yes in spacemacs to confirm I allowed access on last.fm. 
This is what I get in spacemacs when I hit `y`:
![image](https://user-images.githubusercontent.com/73663882/195283966-96f4f416-9255-4dce-9229-66684ea64f6b.png)
 I copy everything after `token=` into the `SK` field of .lastfmrc, save it, and restart Spacemacs. 
 For good measure I re-enabled scrobbling just to attempt to reproduce.
 After I play a track for a while and it tries to scrobble, or I try to love a track again, it does the same.
 Is it strictly necessary that emacs be opening the browser window? I was sure entering the info manually would work after a restart of the application.
Here is the output from my Messages buffer, also:
![image](https://user-images.githubusercontent.com/73663882/195286154-7fe63719-435a-47ae-a12d-e1f01393e4a4.png)

**Comment by magicaldave** [comment]
I feel a little silly now having opened an issue for this.
My emacs had the `browse-url-browser-function` set to `browse-url-default-browser`
For whatever reason the default function was undefined on my system so it did nothing.
Changing this accordingly (Firefox) and setting up a new API key caused the whole thing to work as expected.
