### ISSUE TITLE
Vuiet no longer working after Gentoo upgrade to python 3.11

### ISSUE THREAD

**Issue by eklebanow** [mihaiolteanu/vuiet#72]
Does vuiet depend on python?

On my laptop running Gentoo and emacs 28.2 after an update to python 3.11 vuiet is no longer working

**Comment by mihaiolteanu** [comment]
It depends on `youtube-dl`, which is written in Python,
https://github.com/ytdl-org/youtube-dl

What is the error?
Maybe we can crack it :)

Edit: you can try updating `youtube-dl` first, see how that goes.

**Comment by mihaiolteanu** [comment]
Looks like there are/were problems with `youtube-dl` and `python 3.11` on other projects/platforms,
https://github.com/Homebrew/homebrew-core/pull/114949

**Comment by eklebanow** [comment]
Are there similar issues if you use yt-dlp?

I am not getting an error but vuiet will not start in emacs 28.2 in Gentoo.  It was working fine before transition to python 3.11.  not only will vuiet not start but it freezes emacs.....

How can I make vuiet use yt-dlp?

How can I troubleshoot why vuiet will not start

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mihaiolteanu** [comment]
```How can I make vuiet use yt-dlp?```
https://github.com/mihaiolteanu/vuiet/issues/69

**Comment by mihaiolteanu** [comment]
Did you update youtube-dl?
https://github.com/mihaiolteanu/vuiet/issues/21

**Comment by eklebanow** [comment]
Can you provide more detail as to how to make vuiet use yt-dlp.  What has to be changed? Where do I find the code to change it to?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mihaiolteanu** [comment]
Changed to yt-dlp as the default with #69 
Please reopen if you still have issues.
