### ISSUE TITLE
Add autoload clauses in the library

### ISSUE THREAD

**Issue by rudolfkral** [mihaiolteanu/vuiet#8]
What do you think about adding autoload to functions that can be condsidered public, such as `vuiet-mode`?

**Comment by mihaiolteanu** [comment]
I know about autoload, I understand it's purpose, but I don't think I quite understand how to use it, and not in the way of "not knowing how to write it".

Where would you put it? `vuiet-mode` is only used for the interactive buffer, and you can have that only after you call `vuiet-artist-info`, for example. Would the answer be "just put ;;;;autoload before all the public functions?".

You can try adding it in a PR, if you would like and see how that goes.

Thanks for your suggestion.

**Comment by rudolfkral** [comment]
I'm looking at it mainly as a way not to have to require the package in Spacemacs after installation. Spacemacs loads it with `use-package` with `:defer t`. That creates an empty `autoloads` file, thus no functions from the package are loaded at startup. 

I'm aware that this is a Spacemacs-specific and use-package-specific issue, but I think defining autoload entries has a chance to improve the experience in general, as it would make it more accessible to more people.

I'm going to try to add a PR, we'll see if that makes sense.

**Comment by mihaiolteanu** [comment]
> I'm aware that this is a Spacemacs-specific and use-package-specific issue, but I think defining autoload entries has a chance to improve the experience in general, as it would make it more accessible to more people.

I agree with your comment.

**Comment by mihaiolteanu** [comment]
Added with commit 748952f
